description: Training CIFAR-10 Robustness

target:
  vc: msrlabs
  cluster: eu1

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - pip install torchnet --user
  - pip install statsmodels --user
  - pip install tqdm --user

code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data/
  remote_dir: datasets/

jobs:
# ================================================================================================

- name: cifar_gaussian_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_gaussian_015 --noise=GaussianNoise --sigma=0.15
  - python3 -m src.test --experiment-name=cifar_gaussian_015 --noise=GaussianNoise --sigma=0.15

- name: cifar_uniform_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_015 --noise=UniformNoise --sigma=0.15
  - python3 -m src.test --experiment-name=cifar_uniform_015 --noise=UniformNoise --sigma=0.15

- name: cifar_laplace_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_laplace_015 --noise=LaplaceNoise --sigma=0.15
  - python3 -m src.test --experiment-name=cifar_laplace_015 --noise=LaplaceNoise --sigma=0.15

- name: cifar_expinf_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_015 --noise=ExpInfNoise --sigma=0.15
  - python3 -m src.test --experiment-name=cifar_expinf_015 --noise=ExpInfNoise --sigma=0.15

- name: cifar_exp1_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_exp1_015 --noise=Exp1Noise --sigma=0.15 --k=100
  - python3 -m src.test --experiment-name=cifar_exp1_015 --noise=Exp1Noise --sigma=0.15 --k=100

# ================================================================================================

- name: cifar_gaussian_035
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_gaussian_035 --noise=GaussianNoise --sigma=0.35
  - python3 -m src.test --experiment-name=cifar_gaussian_035 --noise=GaussianNoise --sigma=0.35

- name: cifar_uniform_035
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_035 --noise=UniformNoise --sigma=0.35
  - python3 -m src.test --experiment-name=cifar_uniform_035 --noise=UniformNoise --sigma=0.35

- name: cifar_laplace_035
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_laplace_035 --noise=LaplaceNoise --sigma=0.35
  - python3 -m src.test --experiment-name=cifar_laplace_035 --noise=LaplaceNoise --sigma=0.35

- name: cifar_expinf_035
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_035 --noise=ExpInfNoise --sigma=0.35
  - python3 -m src.test --experiment-name=cifar_expinf_035 --noise=ExpInfNoise --sigma=0.35

- name: cifar_exp1_035
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_exp1_035 --noise=Exp1Noise --sigma=0.35 --k=100
  - python3 -m src.test --experiment-name=cifar_exp1_035 --noise=Exp1Noise --sigma=0.35 --k=100

# ================================================================================================

- name: cifar_gaussian_025
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_gaussian_025 --noise=GaussianNoise --sigma=0.25
  - python3 -m src.test --experiment-name=cifar_gaussian_025 --noise=GaussianNoise --sigma=0.25

- name: cifar_uniform_025
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_025 --noise=UniformNoise --sigma=0.25
  - python3 -m src.test --experiment-name=cifar_uniform_025 --noise=UniformNoise --sigma=0.25

- name: cifar_laplace_025
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_laplace_025 --noise=LaplaceNoise --sigma=0.25
  - python3 -m src.test --experiment-name=cifar_laplace_025 --noise=LaplaceNoise --sigma=0.25

- name: cifar_expinf_025
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_025 --noise=ExpInfNoise --sigma=0.25
  - python3 -m src.test --experiment-name=cifar_expinf_025 --noise=ExpInfNoise --sigma=0.25

- name: cifar_exp1_025
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_exp1_025 --noise=Exp1Noise --sigma=0.25 --k=100
  - python3 -m src.test --experiment-name=cifar_exp1_025 --noise=Exp1Noise --sigma=0.25 --k=100

# ================================================================================================

- name: cifar_gaussian_05
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_gaussian_05 --noise=GaussianNoise --sigma=0.5
  - python3 -m src.test --experiment-name=cifar_gaussian_05 --noise=GaussianNoise --sigma=0.5

- name: cifar_uniform_05
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_05 --noise=UniformNoise --sigma=0.5
  - python3 -m src.test --experiment-name=cifar_uniform_05 --noise=UniformNoise --sigma=0.5

- name: cifar_laplace_05
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_laplace_05 --noise=LaplaceNoise --sigma=0.5
  - python3 -m src.test --experiment-name=cifar_laplace_05 --noise=LaplaceNoise --sigma=0.5

- name: cifar_expinf_05
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_05 --noise=ExpInfNoise --sigma=0.5
  - python3 -m src.test --experiment-name=cifar_expinf_05 --noise=ExpInfNoise --sigma=0.5

- name: cifar_exp1_05
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_exp1_05 --noise=Exp1Noise --sigma=0.5 --k=100
  - python3 -m src.test --experiment-name=cifar_exp1_05 --noise=Exp1Noise --sigma=0.5 --k=100

# ================================================================================================
