description: Training MNIST Robustness [MLP]

target:
  vc: msrlabs
  cluster: eu1

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - pip install torchnet --user
  - pip install statsmodels --user
  - pip install tqdm --user

code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data/
  remote_dir: datasets/

jobs:

# ================================================================================================

- name: mnist_clean
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_clean --dataset=mnist --noise=Clean --sigma=0.0 --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_clean --dataset=mnist --noise=Clean --sigma=0.0 --model=MLP --p=1

# ================================================================================================

- name: mnist_gaussian_30
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_gaussian_30 --dataset=mnist --noise=GaussianNoise --sigma=3.0 --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_gaussian_30 --dataset=mnist --noise=GaussianNoise --sigma=3.0 --model=MLP --p=1

- name: mnist_uniform_30
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_uniform_30 --dataset=mnist --noise=UniformNoise --sigma=3.0 --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_uniform_30 --dataset=mnist --noise=UniformNoise --sigma=3.0 --model=MLP --p=1

- name: mnist_laplace_30
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_laplace_30 --noise=LaplaceNoise --sigma=3.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_laplace_30 --noise=LaplaceNoise --sigma=3.0 --dataset=mnist --model=MLP --p=1

- name: mnist_lomax_30
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_lomax_30 --dataset=mnist --noise=LomaxNoise --sigma=3.0 --model=MLP --lr=0.01 --p=1 --k=3
  - python3 -m src.test --experiment-name=mnist_lomax_30 --dataset=mnist --noise=LomaxNoise --sigma=3.0 --model=MLP --p=1 --k=3

# ================================================================================================

- name: mnist_gaussian_20
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_gaussian_20 --noise=GaussianNoise --sigma=2.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_gaussian_20 --noise=GaussianNoise --sigma=2.0 --dataset=mnist --model=MLP --p=1

- name: mnist_uniform_20
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_uniform_20 --noise=UniformNoise --sigma=2.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_uniform_20 --noise=UniformNoise --sigma=2.0 --dataset=mnist --model=MLP --p=1

- name: mnist_laplace_20
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_laplace_20 --noise=LaplaceNoise --sigma=2.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_laplace_20 --noise=LaplaceNoise --sigma=2.0 --dataset=mnist --model=MLP --p=1

- name: mnist_lomax_20
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_lomax_20 --noise=LomaxNoise --sigma=2.0 --dataset=mnist --model=MLP --lr=0.01 --p=1 --k=3
  - python3 -m src.test --experiment-name=mnist_lomax_20 --noise=LomaxNoise --sigma=2.0 --dataset=mnist --model=MLP --p=1 --k=3

# ================================================================================================

- name: mnist_gaussian_10
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_gaussian_10 --noise=GaussianNoise --sigma=1.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_gaussian_10 --noise=GaussianNoise --sigma=1.0 --dataset=mnist --model=MLP --p=1

- name: mnist_uniform_10
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_uniform_10 --noise=UniformNoise --sigma=1.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_uniform_10 --noise=UniformNoise --sigma=1.0 --dataset=mnist --model=MLP --p=1

- name: mnist_laplace_10
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_laplace_10 --noise=LaplaceNoise --sigma=1.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_laplace_10 --noise=LaplaceNoise --sigma=1.0 --dataset=mnist --model=MLP --p=1

- name: mnist_lomax_10
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_lomax_10 --noise=LomaxNoise --sigma=1.0 --dataset=mnist --model=MLP --lr=0.01 --p=1 --k=3
  - python3 -m src.test --experiment-name=mnist_lomax_10 --noise=LomaxNoise --sigma=1.0 --dataset=mnist --model=MLP --p=1 --k=3

# ================================================================================================

- name: mnist_gaussian_40
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_gaussian_40 --noise=GaussianNoise --sigma=4.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_gaussian_40 --noise=GaussianNoise --sigma=4.0 --dataset=mnist --model=MLP --p=1

- name: mnist_uniform_40
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_uniform_40 --noise=UniformNoise --sigma=4.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_uniform_40 --noise=UniformNoise --sigma=4.0 --dataset=mnist --model=MLP --p=1

- name: mnist_laplace_40
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_laplace_40 --noise=LaplaceNoise --sigma=4.0 --dataset=mnist --model=MLP --lr=0.01 --p=1
  - python3 -m src.test --experiment-name=mnist_laplace_40 --noise=LaplaceNoise --sigma=4.0 --dataset=mnist --model=MLP --p=1

- name: mnist_lomax_40
  sku: G1
  command:
  - python3 -m src.train --experiment-name=mnist_lomax_40 --noise=LomaxNoise --sigma=4.0 --dataset=mnist --model=MLP --lr=0.01 --p=1 --k=3
  - python3 -m src.test --experiment-name=mnist_lomax_40 --noise=LomaxNoise --sigma=4.0 --dataset=mnist --model=MLP --p=1 --k=3

# ================================================================================================

