description: Training CIFAR-10 Robustness

target:
  vc: msrlabs
  cluster: eu1

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - pip install torchnet --user
  - pip install statsmodels --user
  - pip install tqdm --user

code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data/
  remote_dir: datasets/

jobs:

- name: cifar_uniform_075
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_075 --noise=UniformNoise --sigma=0.75
  - python3 -m src.test --experiment-name=cifar_uniform_075 --noise=UniformNoise --sigma=0.75

- name: cifar_laplace_075
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_laplace_075 --noise=LaplaceNoise --sigma=0.75
  - python3 -m src.test --experiment-name=cifar_laplace_075 --noise=LaplaceNoise --sigma=0.75

- name: cifar_expinf_075
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_075 --noise=ExpInfNoise --sigma=0.75
  - python3 -m src.test --experiment-name=cifar_expinf_075 --noise=ExpInfNoise --sigma=0.75

- name: cifar_uniform_1
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_1 --noise=UniformNoise --sigma=1.0
  - python3 -m src.test --experiment-name=cifar_uniform_1 --noise=UniformNoise --sigma=1.0

- name: cifar_laplace_1
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_laplace_1 --noise=LaplaceNoise --sigma=1.0
  - python3 -m src.test --experiment-name=cifar_laplace_1 --noise=LaplaceNoise --sigma=1.0

- name: cifar_expinf_1
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_1 --noise=ExpInfNoise --sigma=1.0
  - python3 -m src.test --experiment-name=cifar_expinf_1 --noise=ExpInfNoise --sigma=1.0

- name: cifar_uniform_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_015 --noise=UniformNoise --sigma=0.15
  - python3 -m src.test --experiment-name=cifar_uniform_015 --noise=UniformNoise --sigma=0.15

- name: cifar_laplace_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_laplace_015 --noise=LaplaceNoise --sigma=0.15
  - python3 -m src.test --experiment-name=cifar_laplace_015 --noise=LaplaceNoise --sigma=0.15

- name: cifar_expinf_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_015 --noise=ExpInfNoise --sigma=0.15
  - python3 -m src.test --experiment-name=cifar_expinf_015 --noise=ExpInfNoise --sigma=0.15
