description: Training CIFAR-10 Robustness

target:
  vc: msrlabs
  cluster: eu1

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - pip install torchnet --user
  - pip install statsmodels --user
  - pip install tqdm --user

code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data/
  remote_dir: datasets/

jobs:
# ================================================================================================

- name: cifar_expinf_015
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_015 --noise=ExpInfNoise --sigma=0.15 --k=2
  - python3 -m src.test --experiment-name=cifar_expinf_015 --noise=ExpInfNoise --sigma=0.15 --k=2

# ================================================================================================

- name: cifar_expinf_035
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_035 --noise=ExpInfNoise --sigma=0.35 --k=2
  - python3 -m src.test --experiment-name=cifar_expinf_035 --noise=ExpInfNoise --sigma=0.35 --k=2

# ================================================================================================

- name: cifar_expinf_025
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_025 --noise=ExpInfNoise --sigma=0.25 --k=2
  - python3 -m src.test --experiment-name=cifar_expinf_025 --noise=ExpInfNoise --sigma=0.25 --k=2

# ================================================================================================

- name: cifar_expinf_05
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_expinf_05 --noise=ExpInfNoise --sigma=0.5 --k=2
  - python3 -m src.test --experiment-name=cifar_expinf_05 --noise=ExpInfNoise --sigma=0.5 --k=2

# ================================================================================================
