description: Training CIFAR-10 Robustness [L2 matched]

target:
  vc: msrlabs
  cluster: eu1

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - pip install torchnet --user
  - pip install statsmodels --user
  - pip install tqdm --user

code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data/
  remote_dir: datasets/

jobs:
# ================================================================================================
#
#- name: cifar_lomax3_025
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax3_025 --noise=LomaxNoise3 --sigma=0.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax3_025 --noise=LomaxNoise3 --sigma=0.25 --p=2
#
#- name: cifar_lomax1_025
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax1_025 --noise=LomaxNoise1 --sigma=0.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax1_025 --noise=LomaxNoise1 --sigma=0.25 --p=2
#
#- name: cifar_lomax2_025
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax2_025 --noise=LomaxNoise2 --sigma=0.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax2_025 --noise=LomaxNoise2 --sigma=0.25 --p=2
#
#- name: cifar_lomax4_025
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax4_025 --noise=LomaxNoise4 --sigma=0.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax4_025 --noise=LomaxNoise4 --sigma=0.25 --p=2
#

- name: cifar_lomax5_025
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_lomax5_025 --noise=LomaxNoise5 --sigma=0.25 --p=2
  - python3 -m src.test --experiment-name=cifar_lomax5_025 --noise=LomaxNoise5 --sigma=0.25 --p=2

# ================================================================================================
#
#- name: cifar_lomax3_05
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax3_05 --noise=LomaxNoise3 --sigma=0.5 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax3_05 --noise=LomaxNoise3 --sigma=0.5 --p=2
#
#- name: cifar_lomax1_05
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax1_05 --noise=LomaxNoise1 --sigma=0.5 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax1_05 --noise=LomaxNoise1 --sigma=0.5 --p=2
#
#- name: cifar_lomax2_05
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax2_05 --noise=LomaxNoise2 --sigma=0.5 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax2_05 --noise=LomaxNoise2 --sigma=0.5 --p=2
#
#- name: cifar_lomax4_05
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax4_05 --noise=LomaxNoise4 --sigma=0.5 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax4_05 --noise=LomaxNoise4 --sigma=0.5 --p=2
#

- name: cifar_lomax5_05
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_lomax5_05 --noise=LomaxNoise5 --sigma=0.5 --p=2
  - python3 -m src.test --experiment-name=cifar_lomax5_05 --noise=LomaxNoise5 --sigma=0.5 --p=2

# ================================================================================================
#
#- name: cifar_lomax3_075
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax3_075 --noise=LomaxNoise3 --sigma=0.75 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax3_075 --noise=LomaxNoise3 --sigma=0.75 --p=2
#
- name: cifar_lomax1_075
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_lomax1_075 --noise=LomaxNoise1 --sigma=0.75 --p=2
  - python3 -m src.test --experiment-name=cifar_lomax1_075 --noise=LomaxNoise1 --sigma=0.75 --p=2
#
#- name: cifar_lomax2_075
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax2_075 --noise=LomaxNoise2 --sigma=0.75 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax2_075 --noise=LomaxNoise2 --sigma=0.75 --p=2
#
#- name: cifar_lomax4_075
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax4_075 --noise=LomaxNoise4 --sigma=0.75 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax4_075 --noise=LomaxNoise4 --sigma=0.75 --p=2

- name: cifar_lomax5_075
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_lomax5_075 --noise=LomaxNoise5 --sigma=0.75 --p=2
  - python3 -m src.test --experiment-name=cifar_lomax5_075 --noise=LomaxNoise5 --sigma=0.75 --p=2

# ================================================================================================
#
#- name: cifar_lomax3_10
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax3_10 --noise=LomaxNoise3 --sigma=1.0 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax3_10 --noise=LomaxNoise3 --sigma=1.0 --p=2
#
#- name: cifar_lomax1_10
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax1_10 --noise=LomaxNoise1 --sigma=1.0 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax1_10 --noise=LomaxNoise1 --sigma=1.0 --p=2
#
#- name: cifar_lomax2_10
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax2_10 --noise=LomaxNoise2 --sigma=1.0 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax2_10 --noise=LomaxNoise2 --sigma=1.0 --p=2
#
#- name: cifar_lomax4_10
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax4_10 --noise=LomaxNoise4 --sigma=1.0 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax4_10 --noise=LomaxNoise4 --sigma=1.0 --p=2
#

- name: cifar_lomax5_10
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_lomax5_10 --noise=LomaxNoise5 --sigma=1.0 --p=2
  - python3 -m src.test --experiment-name=cifar_lomax5_10 --noise=LomaxNoise5 --sigma=1.0 --p=2

# ================================================================================================
#
#- name: cifar_lomax3_125
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax3_125 --noise=LomaxNoise3 --sigma=1.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax3_125 --noise=LomaxNoise3 --sigma=1.25 --p=2
#
#- name: cifar_lomax1_125
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax1_125 --noise=LomaxNoise1 --sigma=1.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax1_125 --noise=LomaxNoise1 --sigma=1.25 --p=2
#
#- name: cifar_lomax2_125
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax2_125 --noise=LomaxNoise2 --sigma=1.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax2_125 --noise=LomaxNoise2 --sigma=1.25 --p=2
#
#- name: cifar_lomax4_125
#  sku: G1
#  command:
#  - python3 -m src.train --experiment-name=cifar_lomax4_125 --noise=LomaxNoise4 --sigma=1.25 --p=2
#  - python3 -m src.test --experiment-name=cifar_lomax4_125 --noise=LomaxNoise4 --sigma=1.25 --p=2

- name: cifar_lomax5_125
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_lomax5_125 --noise=LomaxNoise5 --sigma=1.25 --p=2
  - python3 -m src.test --experiment-name=cifar_lomax5_125 --noise=LomaxNoise5 --sigma=1.25 --p=2

