description: Training CIFAR-10 Robustness

target:
  vc: msrlabs
  cluster: eu1

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - pip install torchnet --user
  - pip install statsmodels --user
  - pip install tqdm --user

code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data/
  remote_dir: datasets/

jobs:

- name: cifar_foo
  sku: G1
  command:
  - python3 -m src.train --experiment-name=cifar_uniform_075 --noise=UniformNoise --sigma=0.75 --num-epochs=1
