description: Training ImageNet Robustness [Original]

target:
  vc: msrlabspvc9
  cluster: eu1

storage:
  imagenet:
    storage_account_name: tonyduan
    container_name: imagenet

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - pip install torchnet --user
  - pip install statsmodels --user
  - pip install tqdm --user

code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data/
  remote_dir: datasets/

search:
  job_template:
    name: imagenet
    sku: G2
    command:
    - python3 -m src.train
      --noise={noise}
      --sigma={sigma}
      --experiment-name=imagenet_{noise}_{sigma}
      --dataset=imagenet
      --batch-size=64
      --num-epochs=30
  type: grid
  max_trials: 20
  params:
    - name: noise
      spec: discrete
      values: ["GaussianNoise", "UniformNoise", "LaplaceNoise", "LomaxNoise"]
    - name: sigma
      spec: discrete
      values: [0.25, 0.5, 0.75, 1.0, 1.25]

