python3 -m src.train --experiment-name=cifar_expinf_05 \
                     --noise=ExpInfNoise \
                     --sigma=0.5 \
                     --output-dir=ckpts/ 
python3 -m src.train --experiment-name=cifar_laplace_05 \
                     --noise=LaplaceNoise \
                     --sigma=0.5 \
                     --output-dir=ckpts/ 
python3 -m src.train --experiment-name=cifar_uniform_05 \
                     --noise=UniformNoise \
                     --sigma=0.5 \
                     --output-dir=ckpts/ 
